# Generated by Django 5.1.6 on 2025-02-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produce',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='produce',
            name='market',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produce',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produce',
            name='variety',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='database.produce')),
            ],
            options={
                'unique_together': {('produce', 'market', 'arrival_date')},
            },
        ),
    ]
