# Generated by Django 5.1.6 on 2025-02-13 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_produce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
