# Generated by Django 5.1.6 on 2025-02-16 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_produce_max_price_produce_min_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=25)),
                ('District', models.CharField(max_length=25)),
                ('Market', models.CharField(max_length=35)),
            ],
        ),
        migrations.RemoveField(
            model_name='produce',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='modal_price',
        ),
        migrations.AddField(
            model_name='listings',
            name='AskPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_location', to='database.location')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_price', to='database.produce')),
            ],
        ),
    ]
