# Generated by Django 5.1.6 on 2025-02-16 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_location_remove_produce_max_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketprice',
            name='id',
        ),
        migrations.AddField(
            model_name='marketprice',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
