# Generated by Django 5.1.6 on 2025-02-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_marketprice_id_marketprice__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Qty_available',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='metrics',
            field=models.CharField(choices=[('Kg', 'Kilogram'), ('Q', 'Qunital')], default='Q', max_length=10),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='metrics',
            field=models.CharField(choices=[('Kg', 'Kilogram'), ('Q', 'Qunital')], default='Q', max_length=10),
        ),
    ]
