# Generated by Django 5.1.6 on 2025-03-02 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_listings_qty_available_listings_metrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='listings/images')),
                ('_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='database.listings')),
            ],
        ),
    ]
