# Generated by Django 5.1.6 on 2026-04-29 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=25)),
                ('District', models.CharField(max_length=25)),
                ('Market', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('AskPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metrics', models.CharField(choices=[('Kg', 'Kilogram'), ('Q', 'Qunital')], default='Q', max_length=10)),
                ('Qty_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='listings/images')),
                ('_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='marketplace.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('variety', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'unique_together': {('name', 'variety')},
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('metrics', models.CharField(choices=[('Kg', 'Kilogram'), ('Q', 'Qunital')], default='Q', max_length=10)),
                ('modal_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_location', to='marketplace.location')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_price', to='marketplace.produce')),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='marketplace.produce'),
        ),
    ]
