# Generated by Django 5.1.6 on 2026-04-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
