# Generated by Django 5.1.6 on 2025-02-15 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_individualprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
