# Generated by Django 5.1.6 on 2025-02-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('farm', 'Farm'), ('organization', 'Organization')], max_length=20),
        ),
    ]
