# Generated by Django 5.1.6 on 2025-03-08 05:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualBuyerProfile',
            fields=[
                ('individualprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.individualprofile')),
            ],
            bases=('users.individualprofile',),
        ),
        migrations.CreateModel(
            name='IndividualProducerProfile',
            fields=[
                ('individualprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.individualprofile')),
                ('farmArea', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            bases=('users.individualprofile',),
        ),
        migrations.RenameField(
            model_name='farmprofile',
            old_name='farm_location',
            new_name='farmLocation',
        ),
        migrations.RenameField(
            model_name='farmprofile',
            old_name='farm_name',
            new_name='farmName',
        ),
        migrations.RenameField(
            model_name='farmprofile',
            old_name='farm_size',
            new_name='farmSize',
        ),
        migrations.RenameField(
            model_name='organizationprofile',
            old_name='organization_name',
            new_name='organizationName',
        ),
        migrations.RenameField(
            model_name='organizationprofile',
            old_name='organization_type',
            new_name='organizationType',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='organization_description',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='organization_website',
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='aboutUs',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='farmArea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='heroImg',
            field=models.ImageField(default='', upload_to='hero/IMG/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='location',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='profileImg',
            field=models.ImageField(default='', upload_to='profile/IMG/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='tagline',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='aboutMe',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='heroImg',
            field=models.ImageField(default='', upload_to='hero/IMG/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='location',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='profileImg',
            field=models.ImageField(default='', upload_to='profile/IMG/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='tagline',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='aboutUs',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='heroImg',
            field=models.ImageField(default='', upload_to='hero/IMG/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='location',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='profileImg',
            field=models.ImageField(default='', upload_to='profile/IMG/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='tagline',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_category',
            field=models.CharField(choices=[('individual', 'Individual'), ('organisation', 'Organisation')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('producer', 'Producer'), ('buyer', 'Buyer')], max_length=20, null=True),
        ),
    ]
