# Generated by Django 5.1.6 on 2025-03-08 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_individualbuyerprofile_individualproducerprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmprofile',
            name='farmLocation',
        ),
        migrations.RemoveField(
            model_name='farmprofile',
            name='farmSize',
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='farmArea',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in acres or hectares', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
