# Generated by Django 5.1.6 on 2025-03-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_farmprofile_heroimg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmprofile',
            old_name='aboutUs',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='individualprofile',
            old_name='aboutMe',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='organizationprofile',
            old_name='aboutUs',
            new_name='about',
        ),
    ]
