# Generated by Django 5.1.6 on 2025-03-08 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_aboutus_farmprofile_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmprofile',
            name='farmArea',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Size in acres or hectares', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='individualproducerprofile',
            name='farmArea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
