# Generated by Django 5.1.6 on 2026-04-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_category',
            field=models.CharField(choices=[('individual', 'individual'), ('organisation', 'organisation')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('producer', 'producer'), ('buyer', 'buyer')], max_length=20, null=True),
        ),
    ]
